name: Flutter CI

# Trigger this every time you push code or open a Pull Request
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # Runs on a virtual cloud computer

    steps:
      - uses: actions/checkout@v4 # Gets your code

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Check for Code Issues (Linter)
        run: flutter analyze

      - name: Run Unit Tests
        run: flutter test
        
      - name: Build Android APK (To ensure no build errors)
        run: flutter build apk --debug